language: generic

sudo: required

services:
  - docker
  
before_install:
  - docker build -t dante01yoon/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true dante01yoon/react-test-app npm run test

after_success:
  - docker build -t dante01yoon/docker-frontend ./frontend
  - docker build -t dante01yoon/docker-backend ./backend
  - docker build -t dante01yoon/nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push dante01yoon/docker-frontend
  - docker push dante01yoon/docker-backend
  - docker push dante01yoon/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  



  